# Generated by Django 5.0.10 on 2024-12-23 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='section_content/', verbose_name='Изображение')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_content', to='sections.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Контент раздела',
                'verbose_name_plural': 'Контент разделов',
                'ordering': ['id'],
            },
        ),
    ]
