# Generated by Django 5.0.10 on 2024-12-23 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectioncontent',
            name='image',
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Test description')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Question')),
                ('answer', models.CharField(blank=True, max_length=40, null=True, verbose_name='Answer')),
                ('test_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section', verbose_name='Тест разделов')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['test_section'],
            },
        ),
    ]
